name: PR/push checks

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --verbose

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
