name: pr-checker

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: cargo build --verbose --features=ispc
      - name: Run tests
        run: cargo test --verbose

