name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install ispc
        run: |
          wget https://github.com/ispc/ispc/releases/download/v1.17.0/ispc-v1.17.0-linux.tar.gz
          tar -xvf ispc-v1.17.0-linux.tar.gz
          echo "$(pwd)/ispc-v1.17.0-linux/bin" >> $GITHUB_PATH
      - name: Test ispc
        run: ispc --version
      - name: Build
        run: cargo build --verbose --features=ispc --release
      - name: Run tests
        run: cargo test --release --verbose
      - name: login
        run: cargo login ${{ secrets.CARGO_TOKEN }}
      - name: publish
        run: cargo publish
